# Generated by Django 4.1 on 2022-09-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='cumpleanios',
            new_name='nacimiento',
        ),
    ]
