# Generated by Django 4.1 on 2022-09-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0003_alter_clientes_correo_alter_clientes_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='correo',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nacimiento',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=256),
        ),
    ]
