# Generated by Django 4.1 on 2022-09-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0004_alter_clientes_correo_alter_clientes_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=64),
        ),
    ]
