# Generated by Django 4.1 on 2022-10-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0005_alter_clientes_correo_alter_clientes_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='cumpleanios',
            new_name='cumpleaños',
        ),
        migrations.RenameField(
            model_name='resenia',
            old_name='resenia',
            new_name='reseña',
        ),
    ]
