# Generated by Django 4.1 on 2022-10-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0006_rename_clientes_cliente_rename_empleados_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='pequeña_reseña',
            field=models.TextField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
