# Generated by Django 4.1 on 2022-10-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0007_stock_pequeña_reseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='pequeña_reseña',
            field=models.TextField(max_length=300),
        ),
    ]
