# Generated by Django 4.1 on 2022-10-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0010_resenia_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
