# Generated by Django 4.1 on 2022-10-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0016_remove_resenia_user_resenia_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imgstock'),
        ),
    ]
