# Generated by Django 4.1 on 2022-10-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0020_remove_resenia_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
    ]
