# Generated by Django 4.1 on 2022-10-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0022_avatar_user_resenia_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='imagen',
        ),
    ]
