# Generated by Django 4.1 on 2022-10-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0028_resenia_fecha_posteo_resenia_imagen_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resenia',
        ),
    ]
