# Generated by Django 4.1 on 2022-10-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0030_resenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resenia',
            name='user',
        ),
        migrations.AddField(
            model_name='resenia',
            name='fecha_posteo',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resenia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
