# Generated by Django 4.1 on 2022-10-11 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APP_Libreria', '0031_remove_resenia_user_resenia_fecha_posteo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resenia',
            name='fecha_posteo',
        ),
        migrations.RemoveField(
            model_name='resenia',
            name='imagen',
        ),
        migrations.AddField(
            model_name='resenia',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
