# Generated by Django 4.1 on 2022-10-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0032_remove_resenia_fecha_posteo_remove_resenia_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='nombre_libro',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
