# Generated by Django 4.1 on 2022-10-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Libreria', '0033_imagen_nombre_libro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resenia',
            name='user',
        ),
    ]
